# Generated by Django 3.2.9 on 2022-09-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
